version: '3.8'
services:
  cart-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cartdb
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: cart-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: